import Navber from "@/components/common/Navber";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="max-w-[800px] mx-auto">
      <Navber />
      <section className="mt-5 px-3 py-2 ">{children}</section>
    </main>
  );
}
